version: '1'
services:
  ledger:
    image: ledger:latest
    ports:
      - 80:80
    restart: on-failure
    volumes:
      - app:/usr/src/app/
    environment:
      - LOCAL=true
    networks:
      - ledger
    container_name: ledger

volumes:
  app:
  db:


networks:
  ledger:
    driver: bridge
